// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gpjnarfhtjlzznljxkvv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imdwam5hcmZodGpsenpubGp4a3Z2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NTgzNjgzNjksImV4cCI6MjA3Mzk0NDM2OX0.mIqO_L3EN075OZvRKpXRx-2eds8SQH95B5RQ3Ae24Rs";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});